# Generated by Django 3.1.8 on 2022-02-20 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amtdep',
            old_name='amount',
            new_name='acc',
        ),
    ]
