# Generated by Django 3.1.8 on 2022-02-21 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_amtdep_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amtfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=12)),
                ('accno', models.IntegerField()),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='amtdep',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 21, 12, 33, 3, 986795)),
        ),
    ]
