# Generated by Django 3.1.8 on 2022-02-21 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_auto_20220221_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amtdep',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 21, 13, 20, 28, 396871)),
        ),
        migrations.AlterField(
            model_name='amtfer',
            name='accno',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='amtfer',
            name='bal',
            field=models.PositiveBigIntegerField(),
        ),
    ]
