# Generated by Django 3.1.8 on 2022-02-21 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_auto_20220221_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amtdep',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 21, 13, 22, 23, 750839)),
        ),
        migrations.AlterField(
            model_name='amtfer',
            name='name',
            field=models.CharField(max_length=225),
        ),
    ]
